### PR TITLE
Arm build

### PR DESCRIPTION
**Pull request by Haishi2016**

### CODE REVIEW

**Comment by msftcoderdjw** [comment]
Our integration and local tests still use old ways to generate the images. Should this be changed as well?

**Review by iwangjintian — APPROVED** [review]

**Comment by iwangjintian** [comment]
> Our integration and local tests still use old ways to generate the images. Should this be changed as well?

we can specify the platform as one to load the image from cache to local, like docker buildx build --platform "linux/amd64" -f Dockerfile -t "ghcr.io/eclipse-symphony/symphony-api-multi:latest"  ".." --load

**Review by iwangjintian — CHANGES_REQUESTED** [review]
Hello Haishi, I think jiawei's concern is much valid. To ensure the test pipeline is using the exact same image as the one we publish, I think we can change the build command in localenv mage file:
https://github.com/eclipse-symphony/symphony/blob/6156e30cf4849cfd6c40cc10b2c5865049d50f57/test/localenv/magefile.go#L386
I've tested on my own that we can use buildx to build a single platform image and load it to the local docker, 
docker buildx build --platform "linux/amd64" -f Dockerfile -t "ghcr.io/eclipse-symphony/symphony-api-multi:latest"  ".." --load
The same change applies to k8s.
image
If the image names are changed, please also change the load function correspondingly,
https://github.com/eclipse-symphony/symphony/blob/6156e30cf4849cfd6c40cc10b2c5865049d50f57/test/localenv/magefile.go#L458

**Comment by Haishi2016** [comment]
> > Our integration and local tests still use old ways to generate the images. Should this be changed as well?
> 
> we can specify the platform as one to load the image from cache to local, like docker buildx build --platform "linux/amd64" -f Dockerfile -t "ghcr.io/eclipse-symphony/symphony-api-multi:latest" ".." --load

I've tried with the "--load" switch. The challenge is that after you've built and loaded platform-specific images in local cache, you need to use buildx build imagetool to assemble them into a multi-platform package. But the imagetool doesn't support reading packages from the local cache.

**Comment by Haishi2016** [comment]
> Our integration and local tests still use old ways to generate the images. Should this be changed as well?

Can we handle this in a follow-up PR?

**Comment by msftcoderdjw** [comment]
> > Our integration and local tests still use old ways to generate the images. Should this be changed as well?
> 
> Can we handle this in a follow-up PR?

Sure. Approved this PR.

**Review by msftcoderdjw — APPROVED** [review]

**Comment by iwangjintian** [comment]
I'll change the test pipeline. We can merge the PR.

**Pull request merged**
