### PR TITLE
Fix docs and change fields

### PR DESCRIPTION
**Pull request by FireDefend**
1. change "type" field of catalog to "catalogType".
2. delete "arguments" of Instances.
3. fix some docs

### CODE REVIEW

**Comment by Haishi2016** [comment]
Why changing Type to CatalogType as it's already under the Catalog type?

**Comment by msftcoderdjw** [comment]
@FireDefend please rebase with latest main.

**Comment by msftcoderdjw** [comment]
> Why changing Type to CatalogType as it's already under the Catalog type?

ARM doesn't allow there is `type` field in ARM resource properties. We have to change it with catalogType. This PR is to align with ARM spec. @FireDefend

**Comment by FireDefend** [comment]
> @FireDefend please rebase with latest main.

rebased and fixed tests

**Pull request merged**
